import resend

from .config import EMAIL_FROM, NOTIFY_EMAIL, RESEND_API_KEY

resend.api_key = RESEND_API_KEY

DAY_ABBR = {
    "Monday": "Mon", "Tuesday": "Tue", "Wednesday": "Wed",
    "Thursday": "Thu", "Friday": "Fri", "Saturday": "Sat", "Sunday": "Sun",
}


def send_email(subject: str, html_body: str):
    """Send email via Resend HTTP API."""
    resend.Emails.send({
        "from": EMAIL_FROM,
        "to": [NOTIFY_EMAIL],
        "subject": subject,
        "html": html_body,
    })


def build_email_html(plan: dict) -> str:
    """Build a styled HTML email from a meal plan."""
    week_of = plan.get("week_of", "this week")
    meals = plan.get("meals", [])
    snacks = plan.get("snacks", [])
    ingredients = plan.get("all_ingredients", [])

    meal_rows = ""
    for meal in meals:
        abbr = DAY_ABBR.get(meal.get("day", ""), meal.get("day", "")[:3])
        meal_rows += f"""
        <div style="display:flex;gap:14px;margin-bottom:16px;align-items:flex-start">
          <div style="min-width:40px;height:36px;background:#eff6ff;border-radius:8px;
                      display:flex;align-items:center;justify-content:center;
                      font-size:11px;font-weight:700;color:#2563eb;
                      text-transform:uppercase;flex-shrink:0">{abbr}</div>
          <div style="flex:1">
            <p style="font-size:15px;font-weight:700;color:#0f172a;margin:0 0 3px">{meal.get('name', '')}</p>
            <p style="font-size:13px;color:#64748b;margin:0;line-height:1.5">{meal.get('description', '')}</p>
          </div>
        </div>"""

    snack_pills = "".join(
        f'<span style="background:#f1f5f9;border-radius:20px;padding:6px 14px;'
        f'font-size:13px;color:#475569;display:inline-block;margin:0 6px 6px 0">{s}</span>'
        for s in snacks
    )

    grocery_items = "".join(
        f'<p style="font-size:13px;color:#374151;padding:3px 0;margin:0">'
        f'<span style="color:#2563eb;font-weight:700">· </span>{i}</p>'
        for i in ingredients
    )

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f8fafc;color:#1e293b;margin:0;padding:0">
<div style="max-width:620px;margin:0 auto;background:white">
  <div style="background:linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%);padding:32px 36px;color:white">
    <p style="color:#94a3b8;font-size:12px;letter-spacing:.08em;text-transform:uppercase;margin:0 0 4px">Weekly Meal Planner</p>
    <h1 style="font-size:24px;font-weight:700;margin:0 0 6px;color:white">🍽️ Dinners This Week</h1>
    <p style="color:#64a7d8;font-size:14px;margin:0">Week of {week_of}</p>
  </div>
  <div style="padding:28px 36px">
    <h2 style="font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#64748b;margin:0 0 14px;padding-bottom:8px;border-bottom:1px solid #e2e8f0">This Week's Dinners</h2>
    {meal_rows}
    <h2 style="font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#64748b;margin:28px 0 14px;padding-bottom:8px;border-bottom:1px solid #e2e8f0">Snack Ideas</h2>
    <div style="margin-bottom:8px">{snack_pills}</div>
    <h2 style="font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#64748b;margin:28px 0 14px;padding-bottom:8px;border-bottom:1px solid #e2e8f0">Grocery List</h2>
    <div style="background:#f8fafc;border-radius:12px;padding:20px 24px">{grocery_items}</div>
  </div>
  <div style="padding:20px 36px;border-top:1px solid #e2e8f0">
    <p style="font-size:12px;color:#94a3b8;margin:0">Generated by Meal Planner Bot</p>
  </div>
</div>
</body></html>"""
